### ISSUE TITLE
MapData isn't autogenerated. 

### ISSUE THREAD

**Issue by Wh1t3Rose** [Kxnrl/Mapchooser-Redux#12]
MapData.txt file isn't autogenerated. So therefore I have null-unknown under each map name in the !nominate menu. I have turned off that feature for now so the nominate menu just has the map names and nothing else to make it look more clean. 

I am on the latest 01/05 build

**Comment by ThanhByKyTa** [comment]
@Wh1t3Rose Check sourcemod/configs/mapdata.txt

If not, check the log file.

**Comment by Wh1t3Rose** [comment]
@ThanhByKyTa I moved on and went to UMC as I had other issues with this plugin. Another was the !nominations menu pulling maps not even on the server. People would nominate/vote for them and when the server tried to switch to the voted map, it'd crash because the map wasn't on the server.
