### ISSUE TITLE
nominations_redux.smx log error

### ISSUE THREAD

**Issue by ThanhByKyTa** [Kxnrl/Mapchooser-Redux#13]
L 01/30/2019 - 16:40:47: [SM] Blaming: nominations_redux.smx
L 01/30/2019 - 16:40:47: [SM] Call stack trace:
L 01/30/2019 - 16:40:47: [SM]   [0] Menu.Display
L 01/30/2019 - 16:40:47: [SM]   [1] Line 180, addons/sourcemod/scripting/nominations_redux.sp::AttemptNominate
L 01/30/2019 - 16:40:47: [SM]   [2] Line 139, addons/sourcemod/scripting/nominations_redux.sp::OnClientSayCommand_Post
L 01/30/2019 - 16:42:04: [SM] Exception reported: String formatted incorrectly - parameter 4 (total 3)

My server can't nominate. Can you help me ?

**Comment by ThanhByKyTa** [comment]
67 "MapChooser Redux" (1.6.138) by Kyle
  68 "Map Lister Redux" (1.6.138) by Kyle
  69 "Map Time Extend Redux" (1.6.138) by Kyle
  72 "Nominations Redux" (1.6.138) by Kyle
  73 "Rock The Vote Redux" (1.6.138) by Kyle

**Comment by Kxnrl** [comment]
can u remake this bug?

**Comment by ThanhByKyTa** [comment]
@Kxnrl No but i fixed. I restart server this working

**Comment by Kxnrl** [comment]
something went wrong
