### ISSUE TITLE
Mapdata player limit

### ISSUE THREAD

**Issue by Marius49** [Kxnrl/Mapchooser-Redux#14]
Hello! Can you use the **minplayers** and **maxplayers** fields from the mapdata to set which maps are available for voting? 

I want to use the plugin to set certain maps to be voted when a certain number of players are on the server. For example, if there are more than 30 players online, I want there to be available for vote only **big** maps. If there are less than 30 players, I want there to be available for vote only **small** maps.

**Comment by Kxnrl** [comment]
minplayers "30" -> if player count < 30, map unavailable.
maxplayers "30" -> if player count > 30, map unavailable.

**Comment by Marius49** [comment]
Thank you for your answer! 
It seems that it works but I've encountered a bug while nominating a map. When I nominate the map for the first time it tells me that the map cannot be nominated since there are less than X number of players. If I nominate another map, then change my nomination back to the map with the player limit restriction, I can suddenly nominate that map even if the requirements are not met. Can you take a look at it?
