### ISSUE TITLE
Is there a way to disable the  map vote is starting overlay text?

### ISSUE THREAD

**Issue by Wh1t3Rose** [Kxnrl/Mapchooser-Redux#20]
Is there a way to disable the  map vote is starting overlay text?

Or can you make it so we can adjust where it is  and make the font MUCH MUCH smaller? It's HUGE!! It even runs off the screeen and you can't read it.

Is that what ```mcr_timer_location``` is used for? What values can we use for that cvar?

**Comment by Kxnrl** [comment]
Timer Location of HUD - 0: Hint,  1: Text,  2: Chat,  3: GameText
