### ISSUE TITLE
.bz2 omission and map types

### ISSUE THREAD

**Issue by xhaooy** [Kxnrl/Mapchooser-Redux#27]
Hello, please add a skip in the auto-generate files so that they do not add maps twice(normal name map and map name with .bz2) when creating them.

Please add map group types in voteing, nominations, etc.(before chooseing map). It will be very useful in multimod servers.
thanks and sorry for my not good english.

**Comment by Kxnrl** [comment]
u mean .bz2 in /maps?

**Comment by xhaooy** [comment]
yes

**Comment by Kxnrl** [comment]
why not use fastdl ?

**Comment by kyoto44** [comment]
map groups types addition would be super cool!

**Comment by xhaooy** [comment]
> 
> 
> why not use fastdl ?

its how my server host works and its super useful cuz i dont have to do anything. it auto-create .bz2 files

**Comment by xhaooy** [comment]
> 
> 
> why not use fastdl ?

it is fastdl, but it works differently

**Comment by xhaooy** [comment]
<3
