### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by szogi1910** [Kxnrl/Mapchooser-Redux#28]
Hello
I have a small problem running the plugin.
After uploading all files, I have error logs

`L 01/11/2020 - 10:48:24: [SM] Unable to load plugin "nominations_redux.smx": Native "Pupd_CheckPlugin" was not found
L 01/11/2020 - 10:48:24: [SM] Unable to load plugin "mapchooser_redux.smx": Native "Pupd_CheckPlugin" was not found
L 01/11/2020 - 10:48:24: [SM] Unable to load plugin "maptimelimit_redux.smx": Native "Pupd_CheckPlugin" was not found
L 01/11/2020 - 10:48:24: [SM] Unable to load plugin "rockthevote_redux.smx": Native "GetMapData" was not found
L 01/11/2020 - 10:48:24: [SM] Unable to load plugin "maplister_redux.smx": Native "Pupd_CheckPlugin" was not found`

**Comment by Kxnrl** [comment]
https://build.kxnrl.com/MapChooser-Redux/1.10/MapChooser-Redux-git181-98cd55d.zip

try this

**Comment by oylsister** [comment]
Or you can just simply remove this line in all .sp files
```
public void Pupd_OnCheckAllPlugins()
{
    Pupd_CheckPlugin(false, "https://build.kxnrl.com/updater/MCR/");
}
```
well, this is just my solution great plugin btw.

**Comment by Gelmo** [comment]
The latest build still does not correct this; your latest commit did not account for rockthevote_redux

**Comment by Gelmo** [comment]
Works perfectly now. Thank you!
