### ISSUE TITLE
Compile plugin !

### ISSUE THREAD

**Issue by ThanhByKyTa** [Kxnrl/Mapchooser-Redux#3]
In your code 
#include store
#include shop
So i must install 2 plugin store and shop ?

**Comment by Kxnrl** [comment]
no

**Comment by Kxnrl** [comment]
but requires .inc files to compile

**Comment by ThanhByKyTa** [comment]
okay i will testing

**Comment by ThanhByKyTa** [comment]
//// mapchooser_redux.sp
//
// mapchooser_redux.sp(894) : error 017: undefined symbol "MG_Shop_GetClientMoney"
// mapchooser_redux.sp(909) : error 017: undefined symbol "MG_Shop_GetClientMoney"
// mapchooser_redux.sp(1020) : error 017: undefined symbol "MG_Shop_ClientEarnMoney"

//// nominations_redux.sp
//
// nominations_redux.sp(256) : error 017: undefined symbol "MG_Shop_ClientCostMoney"
//
// 1 Error.

**Comment by Kxnrl** [comment]
u missing shop.inc

**Comment by ThanhByKyTa** [comment]
can you send me file shop.inc?

**Comment by Kxnrl** [comment]
check it in build.sh
