### ISSUE TITLE
Warmup end (can't end)

### ISSUE THREAD

**Issue by Dism0raL** [Kxnrl/Mapchooser-Redux#31]
I have a problem with your plugin.

When the warm-up on the map ends, the first round does not start. The time automatically changes to 28 minutes. The sign “Warming up is in progress” disappears.

It seems that this is due to the fact that I have set "mp_timelimit 30" subtract 2 minutes of warm-up. But this is speculation.

As a result, the first round does not even begin.

I use the standard mapchooser_redux config (full defoult).
I use maplister_redux.cfg with delete maps 0.
Done compile on SM1.10 and use:
forcemapend_redux.sp
mapchooser_redux.sp
maplister_redux.sp
maptimelimit_redux.sp
nominations_redux.sp
rockthevote_redux.sp
I don't know and don't use portdata.sp and build.sh.

If the error is on my side, then I will be glad if you tell me what is the reason.
The plugin worked well on older versions, but my manual translation by adding the lines "ru" worked poorly.

From Russia with love :D
Sry for auto-translate

**Comment by kyoto44** [comment]
Same bug

**Comment by kyoto44** [comment]
Found the problem - just deleted forcemapend_redux.smx and everything working well

**Comment by Kxnrl** [comment]
okay, look like we can not block round end on warmup.

**Comment by IT-CHI** [comment]
2 years passed and no fix?

**Comment by Kxnrl** [comment]
> 

forcemap_end only use for KZ/Surf/Bhop server
