### ISSUE TITLE
Doubt with the mapchooser redux plugin

### ISSUE THREAD

**Issue by crashzk** [Kxnrl/Mapchooser-Redux#32]
I currently have the following plugins enabled:
```
101 "MapChooser Redux" (2.0.196) by Kyle
102 "Nominations Redux" (2.0.196) by Kyle
103 "Rock The Vote Redux" (2.0.196) by Kyle
```
I would like to know, how can I control how many maps go in the map vote, and delete the maps that have been previously.

In other words, I want to exclude the last two maps that have already been played, and include 6 maps in the vote in total, would I do that? I didn't find in the `mapchooser_redux.cfg` config

**Comment by Kxnrl** [comment]
map pool or map cooldown pool?

**Comment by crashzk** [comment]
I believe it is the map pool.

What I want is to add more maps as an option at the time of voting, and always delete the maps that were played before, that is, I add 6 maps to the total, but of those 6 excludes 3 maps that were played before.

**Comment by Kxnrl** [comment]
edit each map's cooldown in mapdata.kv

**Comment by crashzk** [comment]
Worked, thank you.
