### ISSUE TITLE
Can you update mapdata?

### ISSUE THREAD

**Issue by ThanhByKyTa** [Kxnrl/Mapchooser-Redux#6]
Hi @Kxnrl. Can you update file mapdata.txt ?

**Comment by ThanhByKyTa** [comment]
How to remove font white?
![image](https://user-images.githubusercontent.com/33537916/50725759-1da80400-1135-11e9-99e2-12d9df2fa813.png)

**Comment by Kxnrl** [comment]
update your settings in cfg. set desc tag to 1
