### ISSUE TITLE
Difference 1.10 and 1.9?

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [Kxnrl/Mapchooser-Redux#8]
What the difference between 1.10 and 1.9?

**Comment by Kxnrl** [comment]
1.10 was compiled by latest verison of SM1.10.
1.9 too

**Comment by BrutalCSEjziponken** [comment]
Alright thx, one more question, I have  been using the old extended_mapchooser/nominate/rtv but people complain about lags when it starts the process. You think that problem could be fixed by using this one? Running KZ with LOTS of maps.

**Comment by Kxnrl** [comment]
server lag?

**Comment by ZeitZumKiffen** [comment]
@Kxnrl the old map chooser system have problem with memory leak, i think you fix that on your version (script)
